// SPDX-FileCopyrightText: 2026 Samsung Electronics Co., Ltd.
//
// SPDX-License-Identifier: Apache-2.0

/**
 * Project YAML config reader — parses `tizen_*_project.yaml` files for RDS
 * input interest lists (which source files to hash) and input ignore
 * patterns.
 *
 * Ported from `project-yaml-reader.ts`. Each app type's YAML is read into
 * its raw key/value shape, then narrowed down (`toStringArray`/
 * `toStringValue`) to only the keys RDS input scanning actually needs — see
 * the `*InputInterestConfig` typedefs below.
 *
 * No `yaml` package — see docs/rds/RDS_FAST_DEPLOY_PLAN.en.md Part 6. These files
 * are a trivial YAML subset generated by tizen-core: full-line comments,
 * `key: scalar`, `key: []`, and `key:` followed by indented (or
 * unindented — `src_file_patterns`/`test_file_patterns` are emitted with no
 * indentation) `- item` lines. No anchors, no nesting, no multi-line
 * scalars. Verified against real `tz create`-generated
 * tizen_native_project.yaml / tizen_web_project.yaml files.
 *
 * Reference: packages/server/src/features/rds/project-yaml-reader.ts
 *
 * @module core/rds/yaml-reader
 */

const fs = require("fs");
const path = require("path");
const { DEFAULT_INPUT_IGNORE_PATTERNS } = require("./constants");
const { findFiles } = require("./fs-walk");

const NATIVE_YAML = "tizen_native_project.yaml";
const WEB_YAML = "tizen_web_project.yaml";
const DOTNET_YAML = "tizen_dotnet_project.yaml";

// ─── Hand-rolled YAML subset parser ──────────────────────────────────────────

/**
 * Strip one layer of matching double or single quotes.
 *
 * @param {string} value
 * @returns {string}
 */
function unquote(value) {
  if (
    value.length >= 2 &&
    ((value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'")))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

/**
 * Parse the trivial YAML subset used by `tizen_*_project.yaml` into a flat
 * key → value/list map. See the module doc comment for the supported
 * constructs.
 *
 * @param {string} content - raw file content
 * @returns {Record<string, string | string[]>}
 */
function parseProjectYaml(content) {
  const result = {};
  let currentList = null;

  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trimEnd();
    const trimmed = line.trim();

    if (trimmed === "" || trimmed.startsWith("#")) continue;

    const listItemMatch = /^\s*-\s*(.*)$/.exec(line);
    if (listItemMatch && currentList) {
      currentList.push(unquote(listItemMatch[1].trim()));
      continue;
    }

    const keyMatch = /^([A-Za-z0-9_]+):\s*(.*)$/.exec(line);
    if (!keyMatch) continue; // not a recognized construct — ignore

    const [, key, rest] = keyMatch;
    const value = rest.trim();

    if (value === "" || value === "[]") {
      // Either "key: []" or "key:" followed by "- item" lines — both start
      // as an empty list; subsequent list-item lines (if any) populate it.
      currentList = [];
      result[key] = currentList;
    } else {
      result[key] = unquote(value);
      currentList = null;
    }
  }

  return result;
}

/**
 * @param {unknown} value
 * @returns {string[]}
 */
function toStringArray(value) {
  return Array.isArray(value) ? value.filter((v) => typeof v === "string") : [];
}

/**
 * @param {unknown} value
 * @param {string} [defaultValue]
 * @returns {string}
 */
function toStringValue(value, defaultValue = "") {
  return typeof value === "string" ? value : defaultValue;
}

// ─── Find YAML file path ─────────────────────────────────────────────────────

/**
 * Find the *shallowest* file under `rootDir` whose name ends with
 * `extension`. Breadth-first (see fs-walk.js `findFiles`), so for a solution
 * layout `MyApp.Tests/MyApp.Tests.csproj` never wins over `MyApp/MyApp.csproj`
 * merely because it sorts first; dot-directories and `node_modules`/`bin`/
 * `obj` are pruned.
 *
 * @param {string} rootDir
 * @param {string} extension - e.g. ".csproj"
 * @returns {string|null} absolute path, or null if none found
 */
function findFirstFileByExtension(rootDir, extension) {
  const [found] = findFiles(rootDir, (name) => name.endsWith(extension), {
    first: true,
  });
  return found ?? null;
}

/**
 * Find the project YAML file path for a project directory and app type.
 *
 * - native: `<projectDir>/tizen_native_project.yaml`
 * - web: `<projectDir>/tizen_web_project.yaml`
 * - dotnet: `<csprojDir>/tizen_dotnet_project.yaml` — the YAML lives
 *   alongside the `.csproj` file, not at the project root
 *
 * @param {string} projectDir
 * @param {'native'|'web'|'dotnet'} appType
 * @returns {string|null}
 */
function findProjectYamlPath(projectDir, appType) {
  switch (appType) {
    case "native": {
      const yamlPath = path.join(projectDir, NATIVE_YAML);
      return fs.existsSync(yamlPath) ? yamlPath : null;
    }
    case "web": {
      const yamlPath = path.join(projectDir, WEB_YAML);
      return fs.existsSync(yamlPath) ? yamlPath : null;
    }
    case "dotnet": {
      const csprojPath = findFirstFileByExtension(projectDir, ".csproj");
      if (!csprojPath) return null;
      const yamlPath = path.join(path.dirname(csprojPath), DOTNET_YAML);
      return fs.existsSync(yamlPath) ? yamlPath : null;
    }
    default:
      return null;
  }
}

// ─── Per-app-type parsers ────────────────────────────────────────────────────

/**
 * @typedef {object} NativeInputInterestConfig
 * @property {string[]} sources
 * @property {string[]} edcFiles
 * @property {string[]} edcImagesDirs
 * @property {string[]} edcSoundDirs
 * @property {string[]} edcFontDirs
 * @property {string[]} poFiles
 * @property {string[]} resources
 * @property {string[]} libFiles
 * @property {string[]} includeDirs
 * @property {string[]} libDirs
 * @property {string[]} srcFilePatterns
 * @property {string[]} deps
 */

/**
 * Parse `tizen_native_project.yaml` and extract input interest keys.
 *
 * @param {string} yamlPath
 * @returns {Promise<NativeInputInterestConfig>}
 */
async function parseNativeProjectYaml(yamlPath) {
  const raw = parseProjectYaml(await fs.promises.readFile(yamlPath, "utf-8"));
  return {
    sources: toStringArray(raw.sources),
    edcFiles: toStringArray(raw.edc_files),
    edcImagesDirs: toStringArray(raw.edc_images_dirs),
    edcSoundDirs: toStringArray(raw.edc_sound_dirs),
    edcFontDirs: toStringArray(raw.edc_font_dirs),
    poFiles: toStringArray(raw.po_files),
    resources: toStringArray(raw.resources),
    libFiles: toStringArray(raw.lib_files),
    includeDirs: toStringArray(raw.include_dirs),
    libDirs: toStringArray(raw.lib_dirs),
    srcFilePatterns: toStringArray(raw.src_file_patterns),
    deps: toStringArray(raw.deps),
  };
}

/**
 * @typedef {object} WebInputInterestConfig
 * @property {string} projectPath
 * @property {string[]} deps
 * @property {string[]} excludes
 */

/**
 * Parse `tizen_web_project.yaml` and extract input interest keys.
 *
 * @param {string} yamlPath
 * @returns {Promise<WebInputInterestConfig>}
 */
async function parseWebProjectYaml(yamlPath) {
  const raw = parseProjectYaml(await fs.promises.readFile(yamlPath, "utf-8"));
  return {
    projectPath: toStringValue(raw.project_path),
    deps: toStringArray(raw.deps),
    excludes: toStringArray(raw.excludes),
  };
}

/**
 * @typedef {object} DotnetInputInterestConfig
 * @property {string[]} files
 * @property {string[]} resources
 * @property {string[]} srcFilePatterns
 * @property {string[]} deps
 * @property {string} csprojFile
 */

/**
 * Parse `tizen_dotnet_project.yaml` and extract input interest keys.
 *
 * @param {string} yamlPath
 * @returns {Promise<DotnetInputInterestConfig>}
 */
async function parseDotnetProjectYaml(yamlPath) {
  const raw = parseProjectYaml(await fs.promises.readFile(yamlPath, "utf-8"));
  return {
    files: toStringArray(raw.files),
    resources: toStringArray(raw.resources),
    srcFilePatterns: toStringArray(raw.src_file_patterns),
    deps: toStringArray(raw.deps),
    csprojFile: toStringValue(raw.csproj_file),
  };
}

// ─── Unified API ──────────────────────────────────────────────────────────────

/**
 * @typedef {
 *   {appType: 'native', config: NativeInputInterestConfig} |
 *   {appType: 'web', config: WebInputInterestConfig} |
 *   {appType: 'dotnet', config: DotnetInputInterestConfig}
 * } InputInterestConfig
 */

/**
 * Read the input interest configuration from a project's YAML file.
 *
 * Unlike the extension's version, `appType` is required rather than
 * auto-detected — every caller in this port already has it in hand (RDS
 * entry points call `detectAppType()` once for eligibility gating and reuse
 * the result), so re-deriving it here would just be a second, redundant
 * filesystem scan.
 *
 * @param {string} projectDir
 * @param {'native'|'web'|'dotnet'} appType
 * @returns {Promise<InputInterestConfig>}
 * @throws {Error} if the YAML file cannot be found
 */
async function readInputInterestConfig(projectDir, appType) {
  const yamlPath = findProjectYamlPath(projectDir, appType);
  if (!yamlPath) {
    throw new Error(
      `Project YAML file not found for ${appType} project at ${projectDir}`,
    );
  }

  switch (appType) {
    case "native":
      return {
        appType: "native",
        config: await parseNativeProjectYaml(yamlPath),
      };
    case "web":
      return { appType: "web", config: await parseWebProjectYaml(yamlPath) };
    case "dotnet":
      return {
        appType: "dotnet",
        config: await parseDotnetProjectYaml(yamlPath),
      };
    default:
      throw new Error(`Unsupported app type: ${appType}`);
  }
}

/**
 * @typedef {object} InputIgnoreConfig
 * @property {string[]} patterns
 */

/**
 * Read the input ignore configuration for a project: the default ignore
 * patterns (`constants.js`) plus app-type-specific exclude patterns pulled
 * from the project YAML — `excludes` for web, `src_file_patterns` for
 * native and dotnet.
 *
 * Falls back to the defaults alone (never throws) if the YAML can't be
 * found or read — e.g. the project hasn't been through `tz build` yet.
 *
 * @param {string} projectDir
 * @param {'native'|'web'|'dotnet'} appType
 * @returns {Promise<InputIgnoreConfig>}
 */
async function readInputIgnoreConfig(projectDir, appType) {
  const patterns = [...DEFAULT_INPUT_IGNORE_PATTERNS];

  try {
    const interestConfig = await readInputInterestConfig(projectDir, appType);
    if (interestConfig.appType === "web") {
      patterns.push(...interestConfig.config.excludes);
    } else {
      patterns.push(...interestConfig.config.srcFilePatterns);
    }
  } catch (err) {
    console.warn(
      `[RDS] Failed to read input ignore config from YAML, using defaults: ${err.message}`,
    );
  }

  return { patterns };
}

module.exports = {
  parseProjectYaml,
  findFirstFileByExtension,
  findProjectYamlPath,
  parseNativeProjectYaml,
  parseWebProjectYaml,
  parseDotnetProjectYaml,
  readInputInterestConfig,
  readInputIgnoreConfig,
};
